diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\Charles A. Koenig\AppData\Local\atom\app-1.56.0\atom.exe" --wait
user.email=koenigalfredcharles@gmail.com
user.name=kacharles
user.password=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
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://kacharle:s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@github.com/kacharles/wdd130.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
